// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/audio_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i10;

import 'package:app/enums.dart' as _i9;
import 'package:app/models/models.dart' as _i8;
import 'package:app/providers/providers.dart' as _i7;
import 'package:app/values/values.dart' as _i3;
import 'package:audio_session/audio_session.dart' as _i6;
import 'package:just_audio/just_audio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlaybackEvent_0 extends _i1.SmartFake implements _i2.PlaybackEvent {
  _FakePlaybackEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerState_2 extends _i1.SmartFake implements _i2.PlayerState {
  _FakePlayerState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginationResult_3<T> extends _i1.SmartFake
    implements _i3.PaginationResult<T> {
  _FakePaginationResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i2.AudioPlayer {
  MockAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PlaybackEvent get playbackEvent => (super.noSuchMethod(
        Invocation.getter(#playbackEvent),
        returnValue: _FakePlaybackEvent_0(
          this,
          Invocation.getter(#playbackEvent),
        ),
      ) as _i2.PlaybackEvent);

  @override
  _i4.Stream<_i2.PlaybackEvent> get playbackEventStream => (super.noSuchMethod(
        Invocation.getter(#playbackEventStream),
        returnValue: _i4.Stream<_i2.PlaybackEvent>.empty(),
      ) as _i4.Stream<_i2.PlaybackEvent>);

  @override
  _i4.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i4.Stream<Duration?>.empty(),
      ) as _i4.Stream<Duration?>);

  @override
  _i2.ProcessingState get processingState => (super.noSuchMethod(
        Invocation.getter(#processingState),
        returnValue: _i2.ProcessingState.idle,
      ) as _i2.ProcessingState);

  @override
  _i4.Stream<_i2.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i4.Stream<_i2.ProcessingState>.empty(),
      ) as _i4.Stream<_i2.ProcessingState>);

  @override
  bool get playing => (super.noSuchMethod(
        Invocation.getter(#playing),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<bool> get playingStream => (super.noSuchMethod(
        Invocation.getter(#playingStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  double get volume => (super.noSuchMethod(
        Invocation.getter(#volume),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get volumeStream => (super.noSuchMethod(
        Invocation.getter(#volumeStream),
        returnValue: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  double get speed => (super.noSuchMethod(
        Invocation.getter(#speed),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get speedStream => (super.noSuchMethod(
        Invocation.getter(#speedStream),
        returnValue: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  double get pitch => (super.noSuchMethod(
        Invocation.getter(#pitch),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get pitchStream => (super.noSuchMethod(
        Invocation.getter(#pitchStream),
        returnValue: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  bool get skipSilenceEnabled => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<bool> get skipSilenceEnabledStream => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabledStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  Duration get bufferedPosition => (super.noSuchMethod(
        Invocation.getter(#bufferedPosition),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#bufferedPosition),
        ),
      ) as Duration);

  @override
  _i4.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<_i2.IcyMetadata?> get icyMetadataStream => (super.noSuchMethod(
        Invocation.getter(#icyMetadataStream),
        returnValue: _i4.Stream<_i2.IcyMetadata?>.empty(),
      ) as _i4.Stream<_i2.IcyMetadata?>);

  @override
  _i2.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _FakePlayerState_2(
          this,
          Invocation.getter(#playerState),
        ),
      ) as _i2.PlayerState);

  @override
  _i4.Stream<_i2.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i4.Stream<_i2.PlayerState>.empty(),
      ) as _i4.Stream<_i2.PlayerState>);

  @override
  _i4.Stream<List<_i2.IndexedAudioSource>?> get sequenceStream =>
      (super.noSuchMethod(
        Invocation.getter(#sequenceStream),
        returnValue: _i4.Stream<List<_i2.IndexedAudioSource>?>.empty(),
      ) as _i4.Stream<List<_i2.IndexedAudioSource>?>);

  @override
  _i4.Stream<List<int>?> get shuffleIndicesStream => (super.noSuchMethod(
        Invocation.getter(#shuffleIndicesStream),
        returnValue: _i4.Stream<List<int>?>.empty(),
      ) as _i4.Stream<List<int>?>);

  @override
  _i4.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i4.Stream<int?>.empty(),
      ) as _i4.Stream<int?>);

  @override
  _i4.Stream<_i2.SequenceState?> get sequenceStateStream => (super.noSuchMethod(
        Invocation.getter(#sequenceStateStream),
        returnValue: _i4.Stream<_i2.SequenceState?>.empty(),
      ) as _i4.Stream<_i2.SequenceState?>);

  @override
  bool get hasNext => (super.noSuchMethod(
        Invocation.getter(#hasNext),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPrevious => (super.noSuchMethod(
        Invocation.getter(#hasPrevious),
        returnValue: false,
      ) as bool);

  @override
  _i2.LoopMode get loopMode => (super.noSuchMethod(
        Invocation.getter(#loopMode),
        returnValue: _i2.LoopMode.off,
      ) as _i2.LoopMode);

  @override
  _i4.Stream<_i2.LoopMode> get loopModeStream => (super.noSuchMethod(
        Invocation.getter(#loopModeStream),
        returnValue: _i4.Stream<_i2.LoopMode>.empty(),
      ) as _i4.Stream<_i2.LoopMode>);

  @override
  bool get shuffleModeEnabled => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<bool> get shuffleModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabledStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<int?> get androidAudioSessionIdStream => (super.noSuchMethod(
        Invocation.getter(#androidAudioSessionIdStream),
        returnValue: _i4.Stream<int?>.empty(),
      ) as _i4.Stream<int?>);

  @override
  _i4.Stream<_i2.PositionDiscontinuity> get positionDiscontinuityStream =>
      (super.noSuchMethod(
        Invocation.getter(#positionDiscontinuityStream),
        returnValue: _i4.Stream<_i2.PositionDiscontinuity>.empty(),
      ) as _i4.Stream<_i2.PositionDiscontinuity>);

  @override
  bool get automaticallyWaitsToMinimizeStalling => (super.noSuchMethod(
        Invocation.getter(#automaticallyWaitsToMinimizeStalling),
        returnValue: false,
      ) as bool);

  @override
  bool get canUseNetworkResourcesForLiveStreamingWhilePaused =>
      (super.noSuchMethod(
        Invocation.getter(#canUseNetworkResourcesForLiveStreamingWhilePaused),
        returnValue: false,
      ) as bool);

  @override
  double get preferredPeakBitRate => (super.noSuchMethod(
        Invocation.getter(#preferredPeakBitRate),
        returnValue: 0.0,
      ) as double);

  @override
  bool get allowsExternalPlayback => (super.noSuchMethod(
        Invocation.getter(#allowsExternalPlayback),
        returnValue: false,
      ) as bool);

  @override
  String get webSinkId => (super.noSuchMethod(
        Invocation.getter(#webSinkId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#webSinkId),
        ),
      ) as String);

  @override
  Duration get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#position),
        ),
      ) as Duration);

  @override
  _i4.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<Duration> createPositionStream({
    int? steps = 800,
    Duration? minPeriod = const Duration(milliseconds: 200),
    Duration? maxPeriod = const Duration(milliseconds: 200),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPositionStream,
          [],
          {
            #steps: steps,
            #minPeriod: minPeriod,
            #maxPeriod: maxPeriod,
          },
        ),
        returnValue: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Future<Duration?> setUrl(
    String? url, {
    Map<String, String>? headers,
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUrl,
          [url],
          {
            #headers: headers,
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setFilePath(
    String? filePath, {
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFilePath,
          [filePath],
          {
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setAsset(
    String? assetPath, {
    String? package,
    bool? preload = true,
    Duration? initialPosition,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAsset,
          [assetPath],
          {
            #package: package,
            #preload: preload,
            #initialPosition: initialPosition,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setAudioSource(
    _i2.AudioSource? source, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSource,
          [source],
          {
            #preload: preload,
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setClip({
    Duration? start,
    Duration? end,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setClip,
          [],
          {
            #start: start,
            #end: end,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSkipSilenceEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setSkipSilenceEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setPitch(double? pitch) => (super.noSuchMethod(
        Invocation.method(
          #setPitch,
          [pitch],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLoopMode(_i2.LoopMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setLoopMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setShuffleModeEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setShuffleModeEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> shuffle() => (super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAutomaticallyWaitsToMinimizeStalling(
          bool? automaticallyWaitsToMinimizeStalling) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutomaticallyWaitsToMinimizeStalling,
          [automaticallyWaitsToMinimizeStalling],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setCanUseNetworkResourcesForLiveStreamingWhilePaused(
          bool? canUseNetworkResourcesForLiveStreamingWhilePaused) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCanUseNetworkResourcesForLiveStreamingWhilePaused,
          [canUseNetworkResourcesForLiveStreamingWhilePaused],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setPreferredPeakBitRate(double? preferredPeakBitRate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreferredPeakBitRate,
          [preferredPeakBitRate],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAllowsExternalPlayback(bool? allowsExternalPlayback) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAllowsExternalPlayback,
          [allowsExternalPlayback],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seek(
    Duration? position, {
    int? index,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
          {#index: index},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToNext() => (super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAndroidAudioAttributes(
          _i6.AndroidAudioAttributes? audioAttributes) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAndroidAudioAttributes,
          [audioAttributes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setWebCrossOrigin(_i2.WebCrossOrigin? webCrossOrigin) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWebCrossOrigin,
          [webCrossOrigin],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setWebSinkId(String? webSinkId) => (super.noSuchMethod(
        Invocation.method(
          #setWebSinkId,
          [webSinkId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PlayableProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayableProvider extends _i1.Mock implements _i7.PlayableProvider {
  MockPlayableProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i8.Playable<dynamic>>[],
      ) as List<_i8.Playable<dynamic>>);

  @override
  set playables(List<_i8.Playable<dynamic>>? _playables) => super.noSuchMethod(
        Invocation.setter(
          #playables,
          _playables,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i8.Playable<dynamic>> syncWithVault(dynamic _playables) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithVault,
          [_playables],
        ),
        returnValue: <_i8.Playable<dynamic>>[],
      ) as List<_i8.Playable<dynamic>>);

  @override
  _i8.Playable<dynamic>? byId(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #byId,
        [id],
      )) as _i8.Playable<dynamic>?);

  @override
  _i4.Future<_i3.PaginationResult<_i8.Playable<dynamic>>> paginate(
          _i7.PlayablePaginationConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginate,
          [config],
        ),
        returnValue:
            _i4.Future<_i3.PaginationResult<_i8.Playable<dynamic>>>.value(
                _FakePaginationResult_3<_i8.Playable<dynamic>>(
          this,
          Invocation.method(
            #paginate,
            [config],
          ),
        )),
      ) as _i4.Future<_i3.PaginationResult<_i8.Playable<dynamic>>>);

  @override
  _i4.Future<List<_i8.Playable<dynamic>>> fetchForArtist(
    dynamic artistId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForArtist,
          [artistId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<List<_i8.Playable<dynamic>>>.value(
            <_i8.Playable<dynamic>>[]),
      ) as _i4.Future<List<_i8.Playable<dynamic>>>);

  @override
  _i4.Future<_i3.PaginationResult<_i8.Playable<dynamic>>> paginateByGenre(
    String? genreId, {
    int? page = 1,
    String? sort = 'title',
    _i9.SortOrder? order = _i9.SortOrder.asc,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginateByGenre,
          [genreId],
          {
            #page: page,
            #sort: sort,
            #order: order,
          },
        ),
        returnValue:
            _i4.Future<_i3.PaginationResult<_i8.Playable<dynamic>>>.value(
                _FakePaginationResult_3<_i8.Playable<dynamic>>(
          this,
          Invocation.method(
            #paginateByGenre,
            [genreId],
            {
              #page: page,
              #sort: sort,
              #order: order,
            },
          ),
        )),
      ) as _i4.Future<_i3.PaginationResult<_i8.Playable<dynamic>>>);

  @override
  _i4.Future<List<_i8.Playable<dynamic>>> fetchForAlbum(
    dynamic albumId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForAlbum,
          [albumId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<List<_i8.Playable<dynamic>>>.value(
            <_i8.Playable<dynamic>>[]),
      ) as _i4.Future<List<_i8.Playable<dynamic>>>);

  @override
  _i4.Future<List<_i8.Playable<dynamic>>> fetchForPlaylist(
    dynamic playlistId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForPlaylist,
          [playlistId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<List<_i8.Playable<dynamic>>>.value(
            <_i8.Playable<dynamic>>[]),
      ) as _i4.Future<List<_i8.Playable<dynamic>>>);

  @override
  _i4.Future<List<_i8.Playable<dynamic>>> fetchForPodcast(
    String? podcastId, {
    bool? forceRefresh = false,
    bool? getUpdates = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForPodcast,
          [podcastId],
          {
            #forceRefresh: forceRefresh,
            #getUpdates: getUpdates,
          },
        ),
        returnValue: _i4.Future<List<_i8.Playable<dynamic>>>.value(
            <_i8.Playable<dynamic>>[]),
      ) as _i4.Future<List<_i8.Playable<dynamic>>>);

  @override
  _i4.Future<List<_i8.Playable<dynamic>>> fetchRandom({int? limit = 500}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandom,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i8.Playable<dynamic>>>.value(
            <_i8.Playable<dynamic>>[]),
      ) as _i4.Future<List<_i8.Playable<dynamic>>>);

  @override
  _i4.Future<List<_i8.Playable<dynamic>>> fetchInOrder({
    String? sortField = 'title',
    _i9.SortOrder? order = _i9.SortOrder.asc,
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchInOrder,
          [],
          {
            #sortField: sortField,
            #order: order,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i8.Playable<dynamic>>>.value(
            <_i8.Playable<dynamic>>[]),
      ) as _i4.Future<List<_i8.Playable<dynamic>>>);

  @override
  List<_i8.Playable<dynamic>> parseFromJson(dynamic json) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseFromJson,
          [json],
        ),
        returnValue: <_i8.Playable<dynamic>>[],
      ) as List<_i8.Playable<dynamic>>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DownloadProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadProvider extends _i1.Mock implements _i7.DownloadProvider {
  MockDownloadProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i8.Playable<dynamic>>[],
      ) as List<_i8.Playable<dynamic>>);

  @override
  _i4.Stream<bool> get downloadsClearedStream => (super.noSuchMethod(
        Invocation.getter(#downloadsClearedStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<_i8.Playable<dynamic>> get downloadRemovedStream =>
      (super.noSuchMethod(
        Invocation.getter(#downloadRemovedStream),
        returnValue: _i4.Stream<_i8.Playable<dynamic>>.empty(),
      ) as _i4.Stream<_i8.Playable<dynamic>>);

  @override
  _i4.Stream<_i7.Download> get playableDownloadedStream => (super.noSuchMethod(
        Invocation.getter(#playableDownloadedStream),
        returnValue: _i4.Stream<_i7.Download>.empty(),
      ) as _i4.Stream<_i7.Download>);

  @override
  _i4.Future<String> get downloadsDir => (super.noSuchMethod(
        Invocation.getter(#downloadsDir),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.getter(#downloadsDir),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> download({required _i8.Playable<dynamic>? playable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [],
          {#playable: playable},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i7.Download? getForPlayable(_i8.Playable<dynamic>? playable) =>
      (super.noSuchMethod(Invocation.method(
        #getForPlayable,
        [playable],
      )) as _i7.Download?);

  @override
  bool has({required _i8.Playable<dynamic>? playable}) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [],
          {#playable: playable},
        ),
        returnValue: false,
      ) as bool);

  @override
  void persistMetadata() => super.noSuchMethod(
        Invocation.method(
          #persistMetadata,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void persistMetadataIfNeeded(_i8.Playable<dynamic>? playable) =>
      super.noSuchMethod(
        Invocation.method(
          #persistMetadataIfNeeded,
          [playable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> removeForPlayable(_i8.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeForPlayable,
          [playable],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
