// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/widgets/mini_player_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i11;

import 'package:app/audio_handler.dart' as _i6;
import 'package:app/enums.dart' as _i10;
import 'package:app/models/models.dart' as _i9;
import 'package:app/providers/providers.dart' as _i2;
import 'package:app/values/values.dart' as _i5;
import 'package:audio_service/audio_service.dart' as _i7;
import 'package:audio_session/audio_session.dart' as _i13;
import 'package:just_audio/just_audio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:rxdart/rxdart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDownloadProvider_0 extends _i1.SmartFake
    implements _i2.DownloadProvider {
  _FakeDownloadProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayableProvider_1 extends _i1.SmartFake
    implements _i2.PlayableProvider {
  _FakePlayableProvider_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioPlayer_3 extends _i1.SmartFake implements _i3.AudioPlayer {
  _FakeAudioPlayer_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBehaviorSubject_4<T> extends _i1.SmartFake
    implements _i4.BehaviorSubject<T> {
  _FakeBehaviorSubject_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePublishSubject_5<T> extends _i1.SmartFake
    implements _i4.PublishSubject<T> {
  _FakePublishSubject_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_6<T> extends _i1.SmartFake
    implements _i4.ValueStream<T> {
  _FakeValueStream_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginationResult_7<T> extends _i1.SmartFake
    implements _i5.PaginationResult<T> {
  _FakePaginationResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaybackEvent_8 extends _i1.SmartFake implements _i3.PlaybackEvent {
  _FakePlaybackEvent_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerState_9 extends _i1.SmartFake implements _i3.PlayerState {
  _FakePlayerState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KoelAudioHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockKoelAudioHandler extends _i1.Mock implements _i6.KoelAudioHandler {
  MockKoelAudioHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DownloadProvider get downloadProvider => (super.noSuchMethod(
        Invocation.getter(#downloadProvider),
        returnValue: _FakeDownloadProvider_0(
          this,
          Invocation.getter(#downloadProvider),
        ),
      ) as _i2.DownloadProvider);

  @override
  _i2.PlayableProvider get playableProvider => (super.noSuchMethod(
        Invocation.getter(#playableProvider),
        returnValue: _FakePlayableProvider_1(
          this,
          Invocation.getter(#playableProvider),
        ),
      ) as _i2.PlayableProvider);

  @override
  _i7.AudioServiceRepeatMode get repeatMode => (super.noSuchMethod(
        Invocation.getter(#repeatMode),
        returnValue: _i7.AudioServiceRepeatMode.none,
      ) as _i7.AudioServiceRepeatMode);

  @override
  Duration get sourceLoadTimeout => (super.noSuchMethod(
        Invocation.getter(#sourceLoadTimeout),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#sourceLoadTimeout),
        ),
      ) as Duration);

  @override
  _i3.AudioPlayer get player => (super.noSuchMethod(
        Invocation.getter(#player),
        returnValue: _FakeAudioPlayer_3(
          this,
          Invocation.getter(#player),
        ),
      ) as _i3.AudioPlayer);

  @override
  bool get isRadioMode => (super.noSuchMethod(
        Invocation.getter(#isRadioMode),
        returnValue: false,
      ) as bool);

  @override
  int get currentQueueIndex => (super.noSuchMethod(
        Invocation.getter(#currentQueueIndex),
        returnValue: 0,
      ) as int);

  @override
  set downloadProvider(_i2.DownloadProvider? _downloadProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #downloadProvider,
          _downloadProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set playableProvider(_i2.PlayableProvider? _playableProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #playableProvider,
          _playableProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set repeatMode(_i7.AudioServiceRepeatMode? _repeatMode) => super.noSuchMethod(
        Invocation.setter(
          #repeatMode,
          _repeatMode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.BehaviorSubject<_i7.PlaybackState> get playbackState =>
      (super.noSuchMethod(
        Invocation.getter(#playbackState),
        returnValue: _FakeBehaviorSubject_4<_i7.PlaybackState>(
          this,
          Invocation.getter(#playbackState),
        ),
      ) as _i4.BehaviorSubject<_i7.PlaybackState>);

  @override
  _i4.BehaviorSubject<List<_i7.MediaItem>> get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: _FakeBehaviorSubject_4<List<_i7.MediaItem>>(
          this,
          Invocation.getter(#queue),
        ),
      ) as _i4.BehaviorSubject<List<_i7.MediaItem>>);

  @override
  _i4.BehaviorSubject<String> get queueTitle => (super.noSuchMethod(
        Invocation.getter(#queueTitle),
        returnValue: _FakeBehaviorSubject_4<String>(
          this,
          Invocation.getter(#queueTitle),
        ),
      ) as _i4.BehaviorSubject<String>);

  @override
  _i4.BehaviorSubject<_i7.MediaItem?> get mediaItem => (super.noSuchMethod(
        Invocation.getter(#mediaItem),
        returnValue: _FakeBehaviorSubject_4<_i7.MediaItem?>(
          this,
          Invocation.getter(#mediaItem),
        ),
      ) as _i4.BehaviorSubject<_i7.MediaItem?>);

  @override
  _i4.BehaviorSubject<_i7.AndroidPlaybackInfo> get androidPlaybackInfo =>
      (super.noSuchMethod(
        Invocation.getter(#androidPlaybackInfo),
        returnValue: _FakeBehaviorSubject_4<_i7.AndroidPlaybackInfo>(
          this,
          Invocation.getter(#androidPlaybackInfo),
        ),
      ) as _i4.BehaviorSubject<_i7.AndroidPlaybackInfo>);

  @override
  _i4.BehaviorSubject<_i7.RatingStyle> get ratingStyle => (super.noSuchMethod(
        Invocation.getter(#ratingStyle),
        returnValue: _FakeBehaviorSubject_4<_i7.RatingStyle>(
          this,
          Invocation.getter(#ratingStyle),
        ),
      ) as _i4.BehaviorSubject<_i7.RatingStyle>);

  @override
  _i4.PublishSubject<dynamic> get customEvent => (super.noSuchMethod(
        Invocation.getter(#customEvent),
        returnValue: _FakePublishSubject_5<dynamic>(
          this,
          Invocation.getter(#customEvent),
        ),
      ) as _i4.PublishSubject<dynamic>);

  @override
  _i4.BehaviorSubject<dynamic> get customState => (super.noSuchMethod(
        Invocation.getter(#customState),
        returnValue: _FakeBehaviorSubject_4<dynamic>(
          this,
          Invocation.getter(#customState),
        ),
      ) as _i4.BehaviorSubject<dynamic>);

  @override
  dynamic init({
    required _i2.PlayableProvider? playableProvider,
    required _i2.DownloadProvider? downloadProvider,
  }) =>
      super.noSuchMethod(Invocation.method(
        #init,
        [],
        {
          #playableProvider: playableProvider,
          #downloadProvider: downloadProvider,
        },
      ));

  @override
  void enterRadioMode(_i3.AudioPlayer? radioPlayer) => super.noSuchMethod(
        Invocation.method(
          #enterRadioMode,
          [radioPlayer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void exitRadioMode() => super.noSuchMethod(
        Invocation.method(
          #exitRadioMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRadioPlaybackState({
    required bool? playing,
    required _i7.AudioProcessingState? processingState,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRadioPlaybackState,
          [],
          {
            #playing: playing,
            #processingState: processingState,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  num? getPlaybackPositionFromState(String? playableId) =>
      (super.noSuchMethod(Invocation.method(
        #getPlaybackPositionFromState,
        [playableId],
      )) as num?);

  @override
  void setPlaybackPositionToState(
    String? playableId,
    num? position,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setPlaybackPositionToState,
          [
            playableId,
            position,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> queueAndPlay(_i9.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueAndPlay,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> maybeQueueAndPlay(
    _i9.Playable<dynamic>? playable, {
    dynamic position = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #maybeQueueAndPlay,
          [playable],
          {#position: position},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> queueAfterCurrent(_i9.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueAfterCurrent,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playOrPause() => (super.noSuchMethod(
        Invocation.method(
          #playOrPause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> skipToNext() => (super.noSuchMethod(
        Invocation.method(
          #skipToNext,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> skipToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #skipToPrevious,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> queued(_i9.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #queued,
          [playable],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> removeQueueItemAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeQueueItemAt,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void moveQueueItem(
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #moveQueueItem,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> clearQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setVolume(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> replaceQueue(
    List<_i9.Playable<dynamic>>? playables, {
    bool? shuffle = false,
    bool? autoPlay = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceQueue,
          [playables],
          {
            #shuffle: shuffle,
            #autoPlay: autoPlay,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i7.AudioServiceRepeatMode> rotateRepeatMode() =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateRepeatMode,
          [],
        ),
        returnValue: _i8.Future<_i7.AudioServiceRepeatMode>.value(
            _i7.AudioServiceRepeatMode.none),
      ) as _i8.Future<_i7.AudioServiceRepeatMode>);

  @override
  _i8.Future<void> setRepeatMode(_i7.AudioServiceRepeatMode? repeatMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRepeatMode,
          [repeatMode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cleanUpUponLogout() => (super.noSuchMethod(
        Invocation.method(
          #cleanUpUponLogout,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> queueToBottom(_i9.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueToBottom,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeFromQueue(_i9.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromQueue,
          [playable],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> prepare() => (super.noSuchMethod(
        Invocation.method(
          #prepare,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> prepareFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromMediaId,
          [
            mediaId,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> prepareFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromSearch,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> prepareFromUri(
    Uri? uri, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromUri,
          [
            uri,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromMediaId,
          [
            mediaId,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromSearch,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playFromUri(
    Uri? uri, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromUri,
          [
            uri,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playMediaItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #playMediaItem,
          [mediaItem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> click([_i7.MediaButton? button = _i7.MediaButton.media]) =>
      (super.noSuchMethod(
        Invocation.method(
          #click,
          [button],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addQueueItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItem,
          [mediaItem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addQueueItems(List<_i7.MediaItem>? mediaItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItems,
          [mediaItems],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> insertQueueItem(
    int? index,
    _i7.MediaItem? mediaItem,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertQueueItem,
          [
            index,
            mediaItem,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateQueue(List<_i7.MediaItem>? queue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQueue,
          [queue],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateMediaItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaItem,
          [mediaItem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeQueueItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeQueueItem,
          [mediaItem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> fastForward() => (super.noSuchMethod(
        Invocation.method(
          #fastForward,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> rewind() => (super.noSuchMethod(
        Invocation.method(
          #rewind,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> skipToQueueItem(int? index) => (super.noSuchMethod(
        Invocation.method(
          #skipToQueueItem,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setRating(
    _i7.Rating? rating, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRating,
          [
            rating,
            extras,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setCaptioningEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setCaptioningEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setShuffleMode(_i7.AudioServiceShuffleMode? shuffleMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShuffleMode,
          [shuffleMode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekBackward(bool? begin) => (super.noSuchMethod(
        Invocation.method(
          #seekBackward,
          [begin],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekForward(bool? begin) => (super.noSuchMethod(
        Invocation.method(
          #seekForward,
          [begin],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<dynamic> customAction(
    String? name, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customAction,
          [
            name,
            extras,
          ],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<void> onTaskRemoved() => (super.noSuchMethod(
        Invocation.method(
          #onTaskRemoved,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> onNotificationDeleted() => (super.noSuchMethod(
        Invocation.method(
          #onNotificationDeleted,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i7.MediaItem>> getChildren(
    String? parentMediaId, [
    Map<String, dynamic>? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildren,
          [
            parentMediaId,
            options,
          ],
        ),
        returnValue: _i8.Future<List<_i7.MediaItem>>.value(<_i7.MediaItem>[]),
      ) as _i8.Future<List<_i7.MediaItem>>);

  @override
  _i4.ValueStream<Map<String, dynamic>> subscribeToChildren(
          String? parentMediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToChildren,
          [parentMediaId],
        ),
        returnValue: _FakeValueStream_6<Map<String, dynamic>>(
          this,
          Invocation.method(
            #subscribeToChildren,
            [parentMediaId],
          ),
        ),
      ) as _i4.ValueStream<Map<String, dynamic>>);

  @override
  _i8.Future<_i7.MediaItem?> getMediaItem(String? mediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaItem,
          [mediaId],
        ),
        returnValue: _i8.Future<_i7.MediaItem?>.value(),
      ) as _i8.Future<_i7.MediaItem?>);

  @override
  _i8.Future<List<_i7.MediaItem>> search(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i8.Future<List<_i7.MediaItem>>.value(<_i7.MediaItem>[]),
      ) as _i8.Future<List<_i7.MediaItem>>);

  @override
  _i8.Future<void> androidAdjustRemoteVolume(
          _i7.AndroidVolumeDirection? direction) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidAdjustRemoteVolume,
          [direction],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> androidSetRemoteVolume(int? volumeIndex) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidSetRemoteVolume,
          [volumeIndex],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [PlayableProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayableProvider extends _i1.Mock implements _i2.PlayableProvider {
  MockPlayableProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i9.Playable<dynamic>>[],
      ) as List<_i9.Playable<dynamic>>);

  @override
  set playables(List<_i9.Playable<dynamic>>? _playables) => super.noSuchMethod(
        Invocation.setter(
          #playables,
          _playables,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i9.Playable<dynamic>> syncWithVault(dynamic _playables) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithVault,
          [_playables],
        ),
        returnValue: <_i9.Playable<dynamic>>[],
      ) as List<_i9.Playable<dynamic>>);

  @override
  _i9.Playable<dynamic>? byId(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #byId,
        [id],
      )) as _i9.Playable<dynamic>?);

  @override
  _i8.Future<_i5.PaginationResult<_i9.Playable<dynamic>>> paginate(
          _i2.PlayablePaginationConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginate,
          [config],
        ),
        returnValue:
            _i8.Future<_i5.PaginationResult<_i9.Playable<dynamic>>>.value(
                _FakePaginationResult_7<_i9.Playable<dynamic>>(
          this,
          Invocation.method(
            #paginate,
            [config],
          ),
        )),
      ) as _i8.Future<_i5.PaginationResult<_i9.Playable<dynamic>>>);

  @override
  _i8.Future<List<_i9.Playable<dynamic>>> fetchForArtist(
    dynamic artistId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForArtist,
          [artistId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i8.Future<List<_i9.Playable<dynamic>>>.value(
            <_i9.Playable<dynamic>>[]),
      ) as _i8.Future<List<_i9.Playable<dynamic>>>);

  @override
  _i8.Future<_i5.PaginationResult<_i9.Playable<dynamic>>> paginateByGenre(
    String? genreId, {
    int? page = 1,
    String? sort = 'title',
    _i10.SortOrder? order = _i10.SortOrder.asc,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginateByGenre,
          [genreId],
          {
            #page: page,
            #sort: sort,
            #order: order,
          },
        ),
        returnValue:
            _i8.Future<_i5.PaginationResult<_i9.Playable<dynamic>>>.value(
                _FakePaginationResult_7<_i9.Playable<dynamic>>(
          this,
          Invocation.method(
            #paginateByGenre,
            [genreId],
            {
              #page: page,
              #sort: sort,
              #order: order,
            },
          ),
        )),
      ) as _i8.Future<_i5.PaginationResult<_i9.Playable<dynamic>>>);

  @override
  _i8.Future<List<_i9.Playable<dynamic>>> fetchForAlbum(
    dynamic albumId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForAlbum,
          [albumId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i8.Future<List<_i9.Playable<dynamic>>>.value(
            <_i9.Playable<dynamic>>[]),
      ) as _i8.Future<List<_i9.Playable<dynamic>>>);

  @override
  _i8.Future<List<_i9.Playable<dynamic>>> fetchForPlaylist(
    dynamic playlistId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForPlaylist,
          [playlistId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i8.Future<List<_i9.Playable<dynamic>>>.value(
            <_i9.Playable<dynamic>>[]),
      ) as _i8.Future<List<_i9.Playable<dynamic>>>);

  @override
  _i8.Future<List<_i9.Playable<dynamic>>> fetchForPodcast(
    String? podcastId, {
    bool? forceRefresh = false,
    bool? getUpdates = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForPodcast,
          [podcastId],
          {
            #forceRefresh: forceRefresh,
            #getUpdates: getUpdates,
          },
        ),
        returnValue: _i8.Future<List<_i9.Playable<dynamic>>>.value(
            <_i9.Playable<dynamic>>[]),
      ) as _i8.Future<List<_i9.Playable<dynamic>>>);

  @override
  _i8.Future<List<_i9.Playable<dynamic>>> fetchRandom({int? limit = 500}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandom,
          [],
          {#limit: limit},
        ),
        returnValue: _i8.Future<List<_i9.Playable<dynamic>>>.value(
            <_i9.Playable<dynamic>>[]),
      ) as _i8.Future<List<_i9.Playable<dynamic>>>);

  @override
  _i8.Future<List<_i9.Playable<dynamic>>> fetchInOrder({
    String? sortField = 'title',
    _i10.SortOrder? order = _i10.SortOrder.asc,
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchInOrder,
          [],
          {
            #sortField: sortField,
            #order: order,
            #limit: limit,
          },
        ),
        returnValue: _i8.Future<List<_i9.Playable<dynamic>>>.value(
            <_i9.Playable<dynamic>>[]),
      ) as _i8.Future<List<_i9.Playable<dynamic>>>);

  @override
  List<_i9.Playable<dynamic>> parseFromJson(dynamic json) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseFromJson,
          [json],
        ),
        returnValue: <_i9.Playable<dynamic>>[],
      ) as List<_i9.Playable<dynamic>>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i8.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RadioPlayerProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRadioPlayerProvider extends _i1.Mock
    implements _i2.RadioPlayerProvider {
  MockRadioPlayerProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get playing => (super.noSuchMethod(
        Invocation.getter(#playing),
        returnValue: false,
      ) as bool);

  @override
  bool get loading => (super.noSuchMethod(
        Invocation.getter(#loading),
        returnValue: false,
      ) as bool);

  @override
  bool get active => (super.noSuchMethod(
        Invocation.getter(#active),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> play(_i9.RadioStation? station) => (super.noSuchMethod(
        Invocation.method(
          #play,
          [station],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> togglePlayPause() => (super.noSuchMethod(
        Invocation.method(
          #togglePlayPause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void refreshMediaItem() => super.noSuchMethod(
        Invocation.method(
          #refreshMediaItem,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i3.AudioPlayer {
  MockAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackEvent get playbackEvent => (super.noSuchMethod(
        Invocation.getter(#playbackEvent),
        returnValue: _FakePlaybackEvent_8(
          this,
          Invocation.getter(#playbackEvent),
        ),
      ) as _i3.PlaybackEvent);

  @override
  _i8.Stream<_i3.PlaybackEvent> get playbackEventStream => (super.noSuchMethod(
        Invocation.getter(#playbackEventStream),
        returnValue: _i8.Stream<_i3.PlaybackEvent>.empty(),
      ) as _i8.Stream<_i3.PlaybackEvent>);

  @override
  _i8.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i8.Stream<Duration?>.empty(),
      ) as _i8.Stream<Duration?>);

  @override
  _i3.ProcessingState get processingState => (super.noSuchMethod(
        Invocation.getter(#processingState),
        returnValue: _i3.ProcessingState.idle,
      ) as _i3.ProcessingState);

  @override
  _i8.Stream<_i3.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i8.Stream<_i3.ProcessingState>.empty(),
      ) as _i8.Stream<_i3.ProcessingState>);

  @override
  bool get playing => (super.noSuchMethod(
        Invocation.getter(#playing),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<bool> get playingStream => (super.noSuchMethod(
        Invocation.getter(#playingStream),
        returnValue: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  double get volume => (super.noSuchMethod(
        Invocation.getter(#volume),
        returnValue: 0.0,
      ) as double);

  @override
  _i8.Stream<double> get volumeStream => (super.noSuchMethod(
        Invocation.getter(#volumeStream),
        returnValue: _i8.Stream<double>.empty(),
      ) as _i8.Stream<double>);

  @override
  double get speed => (super.noSuchMethod(
        Invocation.getter(#speed),
        returnValue: 0.0,
      ) as double);

  @override
  _i8.Stream<double> get speedStream => (super.noSuchMethod(
        Invocation.getter(#speedStream),
        returnValue: _i8.Stream<double>.empty(),
      ) as _i8.Stream<double>);

  @override
  double get pitch => (super.noSuchMethod(
        Invocation.getter(#pitch),
        returnValue: 0.0,
      ) as double);

  @override
  _i8.Stream<double> get pitchStream => (super.noSuchMethod(
        Invocation.getter(#pitchStream),
        returnValue: _i8.Stream<double>.empty(),
      ) as _i8.Stream<double>);

  @override
  bool get skipSilenceEnabled => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<bool> get skipSilenceEnabledStream => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabledStream),
        returnValue: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  Duration get bufferedPosition => (super.noSuchMethod(
        Invocation.getter(#bufferedPosition),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#bufferedPosition),
        ),
      ) as Duration);

  @override
  _i8.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i8.Stream<Duration>.empty(),
      ) as _i8.Stream<Duration>);

  @override
  _i8.Stream<_i3.IcyMetadata?> get icyMetadataStream => (super.noSuchMethod(
        Invocation.getter(#icyMetadataStream),
        returnValue: _i8.Stream<_i3.IcyMetadata?>.empty(),
      ) as _i8.Stream<_i3.IcyMetadata?>);

  @override
  _i3.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _FakePlayerState_9(
          this,
          Invocation.getter(#playerState),
        ),
      ) as _i3.PlayerState);

  @override
  _i8.Stream<_i3.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i8.Stream<_i3.PlayerState>.empty(),
      ) as _i8.Stream<_i3.PlayerState>);

  @override
  _i8.Stream<List<_i3.IndexedAudioSource>?> get sequenceStream =>
      (super.noSuchMethod(
        Invocation.getter(#sequenceStream),
        returnValue: _i8.Stream<List<_i3.IndexedAudioSource>?>.empty(),
      ) as _i8.Stream<List<_i3.IndexedAudioSource>?>);

  @override
  _i8.Stream<List<int>?> get shuffleIndicesStream => (super.noSuchMethod(
        Invocation.getter(#shuffleIndicesStream),
        returnValue: _i8.Stream<List<int>?>.empty(),
      ) as _i8.Stream<List<int>?>);

  @override
  _i8.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i8.Stream<int?>.empty(),
      ) as _i8.Stream<int?>);

  @override
  _i8.Stream<_i3.SequenceState?> get sequenceStateStream => (super.noSuchMethod(
        Invocation.getter(#sequenceStateStream),
        returnValue: _i8.Stream<_i3.SequenceState?>.empty(),
      ) as _i8.Stream<_i3.SequenceState?>);

  @override
  bool get hasNext => (super.noSuchMethod(
        Invocation.getter(#hasNext),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPrevious => (super.noSuchMethod(
        Invocation.getter(#hasPrevious),
        returnValue: false,
      ) as bool);

  @override
  _i3.LoopMode get loopMode => (super.noSuchMethod(
        Invocation.getter(#loopMode),
        returnValue: _i3.LoopMode.off,
      ) as _i3.LoopMode);

  @override
  _i8.Stream<_i3.LoopMode> get loopModeStream => (super.noSuchMethod(
        Invocation.getter(#loopModeStream),
        returnValue: _i8.Stream<_i3.LoopMode>.empty(),
      ) as _i8.Stream<_i3.LoopMode>);

  @override
  bool get shuffleModeEnabled => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<bool> get shuffleModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabledStream),
        returnValue: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  _i8.Stream<int?> get androidAudioSessionIdStream => (super.noSuchMethod(
        Invocation.getter(#androidAudioSessionIdStream),
        returnValue: _i8.Stream<int?>.empty(),
      ) as _i8.Stream<int?>);

  @override
  _i8.Stream<_i3.PositionDiscontinuity> get positionDiscontinuityStream =>
      (super.noSuchMethod(
        Invocation.getter(#positionDiscontinuityStream),
        returnValue: _i8.Stream<_i3.PositionDiscontinuity>.empty(),
      ) as _i8.Stream<_i3.PositionDiscontinuity>);

  @override
  bool get automaticallyWaitsToMinimizeStalling => (super.noSuchMethod(
        Invocation.getter(#automaticallyWaitsToMinimizeStalling),
        returnValue: false,
      ) as bool);

  @override
  bool get canUseNetworkResourcesForLiveStreamingWhilePaused =>
      (super.noSuchMethod(
        Invocation.getter(#canUseNetworkResourcesForLiveStreamingWhilePaused),
        returnValue: false,
      ) as bool);

  @override
  double get preferredPeakBitRate => (super.noSuchMethod(
        Invocation.getter(#preferredPeakBitRate),
        returnValue: 0.0,
      ) as double);

  @override
  bool get allowsExternalPlayback => (super.noSuchMethod(
        Invocation.getter(#allowsExternalPlayback),
        returnValue: false,
      ) as bool);

  @override
  String get webSinkId => (super.noSuchMethod(
        Invocation.getter(#webSinkId),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#webSinkId),
        ),
      ) as String);

  @override
  Duration get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#position),
        ),
      ) as Duration);

  @override
  _i8.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i8.Stream<Duration>.empty(),
      ) as _i8.Stream<Duration>);

  @override
  _i8.Stream<Duration> createPositionStream({
    int? steps = 800,
    Duration? minPeriod = const Duration(milliseconds: 200),
    Duration? maxPeriod = const Duration(milliseconds: 200),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPositionStream,
          [],
          {
            #steps: steps,
            #minPeriod: minPeriod,
            #maxPeriod: maxPeriod,
          },
        ),
        returnValue: _i8.Stream<Duration>.empty(),
      ) as _i8.Stream<Duration>);

  @override
  _i8.Future<Duration?> setUrl(
    String? url, {
    Map<String, String>? headers,
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUrl,
          [url],
          {
            #headers: headers,
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> setFilePath(
    String? filePath, {
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFilePath,
          [filePath],
          {
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> setAsset(
    String? assetPath, {
    String? package,
    bool? preload = true,
    Duration? initialPosition,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAsset,
          [assetPath],
          {
            #package: package,
            #preload: preload,
            #initialPosition: initialPosition,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> setAudioSource(
    _i3.AudioSource? source, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSource,
          [source],
          {
            #preload: preload,
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> setClip({
    Duration? start,
    Duration? end,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setClip,
          [],
          {
            #start: start,
            #end: end,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSkipSilenceEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setSkipSilenceEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setPitch(double? pitch) => (super.noSuchMethod(
        Invocation.method(
          #setPitch,
          [pitch],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setLoopMode(_i3.LoopMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setLoopMode,
          [mode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setShuffleModeEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setShuffleModeEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> shuffle() => (super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAutomaticallyWaitsToMinimizeStalling(
          bool? automaticallyWaitsToMinimizeStalling) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutomaticallyWaitsToMinimizeStalling,
          [automaticallyWaitsToMinimizeStalling],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setCanUseNetworkResourcesForLiveStreamingWhilePaused(
          bool? canUseNetworkResourcesForLiveStreamingWhilePaused) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCanUseNetworkResourcesForLiveStreamingWhilePaused,
          [canUseNetworkResourcesForLiveStreamingWhilePaused],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setPreferredPeakBitRate(double? preferredPeakBitRate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreferredPeakBitRate,
          [preferredPeakBitRate],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAllowsExternalPlayback(bool? allowsExternalPlayback) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAllowsExternalPlayback,
          [allowsExternalPlayback],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seek(
    Duration? position, {
    int? index,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
          {#index: index},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekToNext() => (super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAndroidAudioAttributes(
          _i13.AndroidAudioAttributes? audioAttributes) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAndroidAudioAttributes,
          [audioAttributes],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setWebCrossOrigin(_i3.WebCrossOrigin? webCrossOrigin) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWebCrossOrigin,
          [webCrossOrigin],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setWebSinkId(String? webSinkId) => (super.noSuchMethod(
        Invocation.method(
          #setWebSinkId,
          [webSinkId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
